import { sameStory } from "../src/lib/market/events";
const A = { title: "Fed holds rates steady as bitcoin tests the $77,000 support level", entities: ["Federal Reserve","Bitcoin"], event_type: "monetary_policy" };
const B = { title: "Spot bitcoin ETFs see record $77,000 per-minute outflows as BTC slides", entities: ["BlackRock","Bitcoin","ETF"], event_type: "fund_flows" };
const C = { title: "Bitcoin ETF outflows accelerate, BTC drops toward $77,000", entities: ["Bitcoin","ETF"], event_type: "fund_flows" };
const D = { title: "Fed keeps rates unchanged; bitcoin holds $77,000 support", entities: ["Fed","Bitcoin"], event_type: "monetary_policy" };
const E = { title: "Bitcoin miner Marathon reports Q3 loss with BTC near $77,000", entities:["Marathon","Bitcoin"], event_type:"earnings" };
const pairs: [string, any, any][] = [["A(Fed) vs B(ETF flows)",A,B],["A(Fed) vs D(Fed dup)",A,D],["B vs C (ETF dup)",B,C],["A(Fed) vs E(earnings)",A,E],["B(ETF) vs E(earnings)",B,E]];
for (const [label,x,y] of pairs) console.log(sameStory(x as any,y as any) ? "MERGED  " : "SEPARATE", label);
import { eventSimilarity } from "../src/lib/market/events";
for (const [label,x,y] of pairs) console.log("  sim", label, eventSimilarity(x as any,y as any).toFixed(2));
