/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedIntelligenceRouteImport } from './routes/_authenticated/intelligence'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedAdminSearchTestRouteImport } from './routes/_authenticated/admin_.search-test'
import { Route as AuthenticatedRadarsIndexRouteImport } from './routes/_authenticated/radars.index'
import { Route as AuthenticatedRadarsRadarIdRouteImport } from './routes/_authenticated/radars.$radarId'
import { Route as AuthenticatedRadarsNewRouteImport } from './routes/_authenticated/radars.new'
import { Route as ApiTestOpenaiSearchLoopRouteImport } from './routes/api/test/openai-search-loop'
import { Route as ApiTestOpenaiWebSearchRouteImport } from './routes/api/test/openai-web-search'
import { Route as ApiPublicMonitoringProbeRouteImport } from './routes/api/public/monitoring/probe'
import { Route as ApiPublicMonitoringReapRouteImport } from './routes/api/public/monitoring/reap'
import { Route as ApiPublicMonitoringResumeRouteImport } from './routes/api/public/monitoring/resume'
import { Route as ApiPublicMonitoringTickRouteImport } from './routes/api/public/monitoring/tick'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntelligenceRoute =
  AuthenticatedIntelligenceRouteImport.update({
    id: '/intelligence',
    path: '/intelligence',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedAdminSearchTestRoute =
  AuthenticatedAdminSearchTestRouteImport.update({
    id: '/admin_/search-test',
    path: '/admin/search-test',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRadarsIndexRoute =
  AuthenticatedRadarsIndexRouteImport.update({
    id: '/radars/',
    path: '/radars/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRadarsRadarIdRoute =
  AuthenticatedRadarsRadarIdRouteImport.update({
    id: '/radars/$radarId',
    path: '/radars/$radarId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRadarsNewRoute = AuthenticatedRadarsNewRouteImport.update({
  id: '/radars/new',
  path: '/radars/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiTestOpenaiSearchLoopRoute = ApiTestOpenaiSearchLoopRouteImport.update({
  id: '/api/test/openai-search-loop',
  path: '/api/test/openai-search-loop',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestOpenaiWebSearchRoute = ApiTestOpenaiWebSearchRouteImport.update({
  id: '/api/test/openai-web-search',
  path: '/api/test/openai-web-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMonitoringProbeRoute =
  ApiPublicMonitoringProbeRouteImport.update({
    id: '/api/public/monitoring/probe',
    path: '/api/public/monitoring/probe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMonitoringReapRoute = ApiPublicMonitoringReapRouteImport.update({
  id: '/api/public/monitoring/reap',
  path: '/api/public/monitoring/reap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMonitoringResumeRoute =
  ApiPublicMonitoringResumeRouteImport.update({
    id: '/api/public/monitoring/resume',
    path: '/api/public/monitoring/resume',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMonitoringTickRoute = ApiPublicMonitoringTickRouteImport.update({
  id: '/api/public/monitoring/tick',
  path: '/api/public/monitoring/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/intelligence': typeof AuthenticatedIntelligenceRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/search-test': typeof AuthenticatedAdminSearchTestRoute
  '/radars/$radarId': typeof AuthenticatedRadarsRadarIdRoute
  '/radars/new': typeof AuthenticatedRadarsNewRoute
  '/api/test/openai-search-loop': typeof ApiTestOpenaiSearchLoopRoute
  '/api/test/openai-web-search': typeof ApiTestOpenaiWebSearchRoute
  '/radars/': typeof AuthenticatedRadarsIndexRoute
  '/api/public/monitoring/probe': typeof ApiPublicMonitoringProbeRoute
  '/api/public/monitoring/reap': typeof ApiPublicMonitoringReapRoute
  '/api/public/monitoring/resume': typeof ApiPublicMonitoringResumeRoute
  '/api/public/monitoring/tick': typeof ApiPublicMonitoringTickRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/intelligence': typeof AuthenticatedIntelligenceRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/search-test': typeof AuthenticatedAdminSearchTestRoute
  '/radars/$radarId': typeof AuthenticatedRadarsRadarIdRoute
  '/radars/new': typeof AuthenticatedRadarsNewRoute
  '/api/test/openai-search-loop': typeof ApiTestOpenaiSearchLoopRoute
  '/api/test/openai-web-search': typeof ApiTestOpenaiWebSearchRoute
  '/radars': typeof AuthenticatedRadarsIndexRoute
  '/api/public/monitoring/probe': typeof ApiPublicMonitoringProbeRoute
  '/api/public/monitoring/reap': typeof ApiPublicMonitoringReapRoute
  '/api/public/monitoring/resume': typeof ApiPublicMonitoringResumeRoute
  '/api/public/monitoring/tick': typeof ApiPublicMonitoringTickRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/intelligence': typeof AuthenticatedIntelligenceRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/admin_/search-test': typeof AuthenticatedAdminSearchTestRoute
  '/_authenticated/radars/$radarId': typeof AuthenticatedRadarsRadarIdRoute
  '/_authenticated/radars/new': typeof AuthenticatedRadarsNewRoute
  '/api/test/openai-search-loop': typeof ApiTestOpenaiSearchLoopRoute
  '/api/test/openai-web-search': typeof ApiTestOpenaiWebSearchRoute
  '/_authenticated/radars/': typeof AuthenticatedRadarsIndexRoute
  '/api/public/monitoring/probe': typeof ApiPublicMonitoringProbeRoute
  '/api/public/monitoring/reap': typeof ApiPublicMonitoringReapRoute
  '/api/public/monitoring/resume': typeof ApiPublicMonitoringResumeRoute
  '/api/public/monitoring/tick': typeof ApiPublicMonitoringTickRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/pricing'
    | '/reset-password'
    | '/admin'
    | '/alerts'
    | '/billing'
    | '/dashboard'
    | '/intelligence'
    | '/onboarding'
    | '/settings'
    | '/auth/callback'
    | '/admin/search-test'
    | '/radars/$radarId'
    | '/radars/new'
    | '/api/test/openai-search-loop'
    | '/api/test/openai-web-search'
    | '/radars/'
    | '/api/public/monitoring/probe'
    | '/api/public/monitoring/reap'
    | '/api/public/monitoring/resume'
    | '/api/public/monitoring/tick'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/pricing'
    | '/reset-password'
    | '/admin'
    | '/alerts'
    | '/billing'
    | '/dashboard'
    | '/intelligence'
    | '/onboarding'
    | '/settings'
    | '/auth/callback'
    | '/admin/search-test'
    | '/radars/$radarId'
    | '/radars/new'
    | '/api/test/openai-search-loop'
    | '/api/test/openai-web-search'
    | '/radars'
    | '/api/public/monitoring/probe'
    | '/api/public/monitoring/reap'
    | '/api/public/monitoring/resume'
    | '/api/public/monitoring/tick'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/pricing'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/alerts'
    | '/_authenticated/billing'
    | '/_authenticated/dashboard'
    | '/_authenticated/intelligence'
    | '/_authenticated/onboarding'
    | '/_authenticated/settings'
    | '/auth/callback'
    | '/_authenticated/admin_/search-test'
    | '/_authenticated/radars/$radarId'
    | '/_authenticated/radars/new'
    | '/api/test/openai-search-loop'
    | '/api/test/openai-web-search'
    | '/_authenticated/radars/'
    | '/api/public/monitoring/probe'
    | '/api/public/monitoring/reap'
    | '/api/public/monitoring/resume'
    | '/api/public/monitoring/tick'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiTestOpenaiSearchLoopRoute: typeof ApiTestOpenaiSearchLoopRoute
  ApiTestOpenaiWebSearchRoute: typeof ApiTestOpenaiWebSearchRoute
  ApiPublicMonitoringProbeRoute: typeof ApiPublicMonitoringProbeRoute
  ApiPublicMonitoringReapRoute: typeof ApiPublicMonitoringReapRoute
  ApiPublicMonitoringResumeRoute: typeof ApiPublicMonitoringResumeRoute
  ApiPublicMonitoringTickRoute: typeof ApiPublicMonitoringTickRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/intelligence': {
      id: '/_authenticated/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof AuthenticatedIntelligenceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/admin_/search-test': {
      id: '/_authenticated/admin_/search-test'
      path: '/admin/search-test'
      fullPath: '/admin/search-test'
      preLoaderRoute: typeof AuthenticatedAdminSearchTestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/radars/': {
      id: '/_authenticated/radars/'
      path: '/radars'
      fullPath: '/radars/'
      preLoaderRoute: typeof AuthenticatedRadarsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/radars/$radarId': {
      id: '/_authenticated/radars/$radarId'
      path: '/radars/$radarId'
      fullPath: '/radars/$radarId'
      preLoaderRoute: typeof AuthenticatedRadarsRadarIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/radars/new': {
      id: '/_authenticated/radars/new'
      path: '/radars/new'
      fullPath: '/radars/new'
      preLoaderRoute: typeof AuthenticatedRadarsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/test/openai-search-loop': {
      id: '/api/test/openai-search-loop'
      path: '/api/test/openai-search-loop'
      fullPath: '/api/test/openai-search-loop'
      preLoaderRoute: typeof ApiTestOpenaiSearchLoopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test/openai-web-search': {
      id: '/api/test/openai-web-search'
      path: '/api/test/openai-web-search'
      fullPath: '/api/test/openai-web-search'
      preLoaderRoute: typeof ApiTestOpenaiWebSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/monitoring/probe': {
      id: '/api/public/monitoring/probe'
      path: '/api/public/monitoring/probe'
      fullPath: '/api/public/monitoring/probe'
      preLoaderRoute: typeof ApiPublicMonitoringProbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/monitoring/reap': {
      id: '/api/public/monitoring/reap'
      path: '/api/public/monitoring/reap'
      fullPath: '/api/public/monitoring/reap'
      preLoaderRoute: typeof ApiPublicMonitoringReapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/monitoring/resume': {
      id: '/api/public/monitoring/resume'
      path: '/api/public/monitoring/resume'
      fullPath: '/api/public/monitoring/resume'
      preLoaderRoute: typeof ApiPublicMonitoringResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/monitoring/tick': {
      id: '/api/public/monitoring/tick'
      path: '/api/public/monitoring/tick'
      fullPath: '/api/public/monitoring/tick'
      preLoaderRoute: typeof ApiPublicMonitoringTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIntelligenceRoute: typeof AuthenticatedIntelligenceRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedAdminSearchTestRoute: typeof AuthenticatedAdminSearchTestRoute
  AuthenticatedRadarsRadarIdRoute: typeof AuthenticatedRadarsRadarIdRoute
  AuthenticatedRadarsNewRoute: typeof AuthenticatedRadarsNewRoute
  AuthenticatedRadarsIndexRoute: typeof AuthenticatedRadarsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIntelligenceRoute: AuthenticatedIntelligenceRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedAdminSearchTestRoute: AuthenticatedAdminSearchTestRoute,
  AuthenticatedRadarsRadarIdRoute: AuthenticatedRadarsRadarIdRoute,
  AuthenticatedRadarsNewRoute: AuthenticatedRadarsNewRoute,
  AuthenticatedRadarsIndexRoute: AuthenticatedRadarsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiTestOpenaiSearchLoopRoute: ApiTestOpenaiSearchLoopRoute,
  ApiTestOpenaiWebSearchRoute: ApiTestOpenaiWebSearchRoute,
  ApiPublicMonitoringProbeRoute: ApiPublicMonitoringProbeRoute,
  ApiPublicMonitoringReapRoute: ApiPublicMonitoringReapRoute,
  ApiPublicMonitoringResumeRoute: ApiPublicMonitoringResumeRoute,
  ApiPublicMonitoringTickRoute: ApiPublicMonitoringTickRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
